[package]
name = "simple_haystack"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8"
actix-multipart = "0.7"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"